language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - python -m textblob.download_corpora
  - python -m nltk.downloader stopwords
script:
  - coverage run --source=. tests.py
  - coveralls
