name: Backend CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        node-version: ${{ matrix.python-version }}

    - name: Install pipenv
      run: sudo pip install pipenv

    - name: Install dependencies using Pipenv
      run: pipenv install --deploy --system

    - name: Download deps
      run: |
          python -m textblob.download_corpora
          python -m nltk.downloader stopwords

    - name: Test moviepepper-backend
      run: |
          coverage run --concurrency=multiprocessing tests.py
          coverage combine
          coveralls
      env:
        CI: true


