name: Backend CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'

    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1

    - name: Install dependencies
      run: |
          pipenv install --dev

    - name: Download deps
      run: |
          pipenv run python -m textblob.download_corpora
          pipenv run python -m nltk.downloader stopwords

    - name: Test moviepepper-backend
      run: |
          pipenv run coverage run --concurrency=multiprocessing tests.py
          pipenv run coverage combine
          pipenv run coveralls
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


